seed = 42          # Random seed for reproducibility
dev_run = false    # Run a small subset of the data for debugging
task = "bc" # bc, cls, reg, tte, mxc (binary, multiclass, regression, time-to-event, mixture-cure)
simulate = false # Regenerate the tokenized dataset
tune = false       # tune the model hyperparameters
use_best = false   # use the best hyperparameters found during tuning
train = true      # train the model
evaluate = false   # Generate test set model performance metrics 
importance = false  # Compute feature importance
plot = false       # Generate plots/figures
compile = false    # Compile the Torch model
proportions = [0.8, 0.1, 0.1] # proportions for train, val, test splits

[path]
dataset = "data/dataset"                           
hyperparameters = "data/model/hyperparameters.json"
checkpoint = "data/model/checkpoint.pt"                
logs = "data/logs"                                 
metrics = "data/results/metrics.parquet"                   
attribution = "data/results/attribution.parquet"                                      
simulation_plot = "data/plots/simulation.png"
importance_plot = "data/plots/importance.png"
metrics_plot = "data/plots/metrics.png"

[simulation]
num_samples = 1000
num_timepoints = 20
num_draws = 0
parameters = [-1.5, 1.5] # can be list[float] or int
intercept = -2.5   # this affects the prevalence
scale = 1.0
parameter_std = 0.1
latent_std = 0.5
observed_std = 0.1
gamma_shape = 1.0
gamma_rate = 1.0

[dataset]
train_size = 0.8
stratify = "label" # TODO unused

[dataloader]
batch_size = 32
num_workers = 0            # > 1 for multiprocessing
pin_memory = true
persistent_workers = false

[model]
hidden_dim = 8
num_heads = 1
num_layers = 2 
dropout = 0.1
bias = false
causal = true

[loss]
ignore_index = -100

[optimizer]
lr = 1e-4
weight_decay = 1e-6
fused = true

[scheduler]
gamma = 0.9

[trainer]
max_epochs = 5
gradient_clip = 1.0
device = "cpu" # auto, cpu, cuda, mps

[tuner]
n_trials = 16
direction = "minimize"
checkpoint = "checkpoint.pt"

[hparams]
path = "hyperparameters.json"
[hparams.max_epochs]
name = "max_epochs"
low = 2
high = 20
[hparams.hidden_dim]
name = "hidden_dim"
low = 6             # 2^6 = 64
high = 10           # 2^10 = 1024
[hparams.num_heads]
name = "num_heads"
low = 1
high = 3
[hparams.num_layers]
name = "num_layers"
low = 1
high = 6
[hparams.dropout]
name = "dropout"
low = 0.0
high = 0.1
[hparams.lr]
name = "lr"
low = 1e-4
high = 1e-2
log = true
[hparams.weight_decay]
name = "weight_decay"
low = 1e-10
high = 1e-2
log = true

[evaluator]
n_bootstraps = 100

[plots]
style = "darkgrid"
font_scale = 1.5
palette = "viridis"
