[main]
seed = 42           # Random seed for reproducibility
dev_run = false     # Run a small subset of the data for debugging
regenerate = true  # Regenerate the tokenized dataset
tune = true        # tune the model hyperparameters
use_best = true     # use the best hyperparameters found during tuning
train = true       # train the model
evaluate = true    # Generate test set model performance metrics 
importance = true   # Compute feature importance
plot = true        # Generate plots/figures
compile = false     # Compile the Torch model
data = "data/"      # Path to the data directory

[tokenizer]
path = "tokenizer"
vocab_size = 2_000 # increase for larger corpus
max_length = 265

[dataset]
path = "rotten_tomatoes"
train_size = 0.8
stratify = "label"

[dataloader]
batch_size = 64
num_workers = 0   # > 1 for multiprocessing
pin_memory = true
persistent_workers = false

[model]
compile = false
embedding_dim = 128
hidden_dim = 128

[loss]
ignore_index = -100
reduction = "mean"

[optimizer]
lr = 1e-5
momentum = 0.9
weight_decay = 1e-6
fused = true

[scheduler]
gamma = 0.9

[trainer]
max_epochs = 5
gradient_clip = 1.0

[tuner]
n_trials = 32
direction = "minimize"
checkpoint = "checkpoint.pt"

[hparams]
path = "hyperparameters.json"
[hparams.max_epochs]
name = "max_epochs"
low = 1
high = 10
[hparams.hidden_dim]
name = "hidden_dim"
low = 6 # 2^6 = 64
high = 10 # 2^10 = 1024
[hparams.lr]
name = "lr"
low = 1e-5
high = 1e-3
log = true
[hparams.weight_decay]
name = "weight_decay"
low = 1e-10
high = 1e-2
log = true

[evaluator]
n_bootstraps = 100
path = "metrics.parquet"

[attribution]
path = "attribution.parquet"
num_samples = 512


[plots]
path = "plots/"
importance = "importance.png"
metrics = "metrics.png"
style = "darkgrid"
font_scale = 1.5
palette = "viridis"