seed = 42         # Random seed for reproducibility
dev_run = false   # Run a small subset of the data for debugging
regenerate = true # Regenerate the tokenized dataset
tune = true      # tune hyperparameters
use_best = true   # use best or default hyperparameters 
train = true      # train model
evaluate = true   # Generate performance metrics from the test set
importance = true # Compute feature importance
plot = true       # Generate plots/figures
data_dir = "data/"

[tokenizer]
path = "tokenizer"
vocab_size = 30_000
max_length = 512

[dataset]
name = "ag_news"
path = "ag_news/"
train_size = 0.8
stratify = "label"

[dataloader]
batch_size = 32
num_workers = 0   # > 1 for multiprocessing
pin_memory = true
persistent_workers = false

[model]
compile = false
embedding_dim = 256
hidden_dim = 256

[optimizer]
lr = 1e-5
momentum = 0.9
weight_decay = 1e-6

[trainer]
max_epochs = 4
gradient_clip = 1.0

[tuner]
n_trials = 32
direction = "minimize"
checkpoint = "checkpoint.pt"
hparams_path = "hyperparameters.json"

[hparams]
[hparams.max_epochs]
name = "max_epochs"
low = 1
high = 5
[hparams.hidden_dim]
name = "hidden_dim"
low = 6 # 2^6 = 64
high = 10 # 2^10 = 1024
[hparams.lr]
name = "lr"
low = 1e-5
high = 1e-3
log = true
[hparams.weight_decay]
name = "weight_decay"
low = 1e-10
high = 1e-2
log = true

[evaluator]
n_bootstraps = 3
path = "metrics.parquet"

[attribution]
path = "attribution.parquet"
num_samples = 1024


[plots]
path = "plots/"
style = "darkgrid"
font_scale = 1.5
palette = "viridis"
importance = "importance.png"